adpyke.codesnap
bmewburn.vscode-intelephense-client
bradlc.vscode-tailwindcss
catppuccin.catppuccin-vsc
christian-kohler.npm-intellisense
christian-kohler.path-intellisense
dlasagno.rasi
ecmel.vscode-html-css
enkia.tokyo-night
esbenp.prettier-vscode
github.copilot
github.copilot-chat
google.colab
hbenl.vscode-mocha-test-adapter
hbenl.vscode-test-explorer
kamikillerto.vscode-colorize
ms-python.debugpy
ms-python.python
ms-python.vscode-pylance
ms-python.vscode-python-envs
ms-toolsai.jupyter
ms-toolsai.jupyter-keymap
ms-toolsai.jupyter-renderers
ms-toolsai.vscode-jupyter-cell-tags
ms-toolsai.vscode-jupyter-slideshow
ms-vscode.cpptools
ms-vscode.test-adapter-converter
nomicfoundation.hardhat-solidity
oderwat.indent-rainbow
pkief.material-icon-theme
rangav.vscode-thunder-client
ritwickdey.liveserver
tal7aouy.rainbow-bracket
usernamehw.errorlens
zignd.html-css-class-completion
